config/routes.rb
Rails.application.routes.draw do
  devise_for :users

    root "users#index"
    resources :users, only: [:index, :show] do
      resources :posts, only: [:index, :new, :create, :show] do
        resources :comments, only: [:new, :create]
        resources :likes, only: [:create]
      end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  after_save :update_comment_counter

  private

  def update_comment_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  after_save :update_likes_counter
  after_destroy :update_likes_counter

  private

  def update_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  belongs_to :author, class_name: 'User'
  has_many :likes
  after_save :update_post_counter

  validates :title, presence: true
  validates :title, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_post_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :comments
  has_many :posts, foreign_key: 'author_id'
  has_many :likes

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def recent_post
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name bio photo])
  end
  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    return unless @comment.save

    redirect_to user_post_path(current_user, @post)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = Like.new(user: current_user, post: @post)
    return unless @like.save

    redirect_to user_post_path(current_user, @post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @like = Like.find_by(user_id: current_user.id)
    @like.destroy
    redirect_to user_post_path(current_user, @post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to user_posts_path(current_user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:text, :title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'application'
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def truncate(text)
    text.length > 200 ? "#{text[0, 200]}..." : text
  end

  def user_already_liked?(post)
    post.likes.find_by(user_id: current_user.id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<h1>Create a new Comment</h1>

<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>
<%= form_with model: [:user, :post, @comment], data: { turbo: false }, local: true do |f| %>
  <div>
    <%= f.label :text %><br>
    <%= f.text_field :text %><br>
    <%= f.hidden_field :user_id, value: params[:user_id] %>
    <%= f.hidden_field :post_id, value: params[:post_id] %>
    <%= f.submit "Comment" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <% if user_signed_in? %>
  <%= link_to "sign_out", destroy_user_session_path, data:{turbo_method: :delete} %>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/standard.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "style", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

   <body>

      <div id = "container">
        <%= yield -%>
      </div>

   </body>

</html>

app/views/likes/_likes_action.html.erb
<%# <% if post.likes.indlude?(current_user.id) %>
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>

<%= form_with model: @like, url: user_post_likes_path(post_id: post.id, user_id: post.author_id), data: { turbo: false }, local: true, scope: :like do |f| %>
  <div>
    <%= f.hidden_field :user_id, value: :user_id %>
    <%= f.hidden_field :post_id, value: :post_id %>
    <%= f.submit "Like this post" %>
  </div>
<% end %>

app/views/posts/_post_info.html.erb
<div class="user-post-div">
<p class="post-title"><%= link_to post.title, user_post_path(user, post) %></p>
<p class="post-text"><%= truncate(post.text)%></p>
<div class="comments-likes">
<p class="post-text"> Comments:<%= post.comments_counter%>,</p>
<p class="post-text"> Likes:<%= post.likes_counter%></p>
</div>
</div>

app/views/posts/index.html.erb
<%= link_to "create new post", new_user_post_path, class:"all-post-btn"  %>
<%= render 'users/user_info', user: @user %>
<% @posts.each do |post| %>
  <%= render 'post_info', user: @user, post: post%>
  <% if post.comments.any? %>
  <ul class= "comment-div">
  <% post.recent_comments.each do |comment| %>
    <li><%= comment.user.name %>: <%= comment.text %></li>
  <% end %>
  </ul>
  <% else %>
  <% end %>
  <% end %>
  <div class="pagination">
  <%= link_to "Pagination", user_posts_path(@user), class:"all-post-btn"  %>
  </div>

app/views/posts/new.html.erb
<%= form_with model:[current_user, @post,] do |form| %>
    <div>
    <%= form.label :title %>
    <%= form.text_field :title%>
    </div>
    <div>
    <%= form.label :text %>
    <%= form.text_field :text%>
    </div>
    <div>
    <%= form.submit%>
    </div>
<% end %>

app/views/posts/show.html.erb
<div class="post-all">
<div class="post-show">
<p class="span"><%= @post.title %> by <%= @post.author.name %></p>
<div class="comments-likes">
<p class="post-text"> Comments:<%= @post.comments_counter%>,</p>
<p class="post-text"> Likes:<%= @post.likes_counter%></p>
</div>
</div>
<p><%= @post.text %></p>
<% if user_already_liked?(@post) %>
<%= button_to "Dislike", user_post_likes_path(current_user, @post), method: :delete, class:"all-post-btn" %>
<% else %>
<%= button_to "Like", user_post_likes_path(current_user, @post), method: :post, class:"all-post-btn"  %>
<% end %>
</div>
<% if @post.comments.any? %>
  <ul class= "comment-div">
  <% @post.comments.each do |comment| %>
    <li><%= comment.user.name %>: <%= comment.text %></li>
  <% end %>
  </ul>
  <% else %>
  <% end %>
  <h2>Add a comment</h2>
  <%= form_with model:[current_user, @post, Comment.new] do |form| %>
    <div>
    <%= form.label :text %>
    <%= form.text_field :text%>
    </div>
    <div>
    <%= form.submit%>
    </div>
<% end %>

app/views/users/_user_info.html.erb
<div class="user-home">
    <div class="user-img-div">
    <img class="user-img" src="<%= user.photo %>">
    </div>
    <div class="user-info">
    <p class="user-name"><%= link_to user.name, user_path(user) %></p>
    <p class="user-num-posts">Number of Posts: <%= user.posts.length %></p>
    </div>
    </div>

app/views/users/index.html.erb
<% @users.each do |user| %>
   <%= render 'user_info', user: user %>
<% end %>

app/views/users/show.html.erb
<%= render 'user_info', user: @user %>
<div class="user-details">
<div class="user-bio-div">
  <p class="bio-tag">Bio</p>
  <p class="bio"><%= @user.bio %></p>
</div>
<% @user.recent_post.each do |post| %>
    <%= render 'posts/post_info', user: @user, post: post %>
<% end %>
<%= link_to "See all post", user_posts_path(@user), class:"all-post-btn"  %>
</div>